patch_size: 192
batch_size: 16
epochs: 3500
lr: 0.0001
scheduler_step_epochs: 1000
validate_every: 500
num_workers: 2
train_preload: True
val_preload: True

models:
  - model:
      name: SR_FastEDSR_Multi
      checkpoint_name: SR_FastEDSR_jpeg_2_64
      params:
        num_blocks: 2
        nf: 64
  - model:
      name: SR_FastEDSR_Multi
      checkpoint_name: SR_FastEDSR_jpeg_4_32
      params:
        num_blocks: 4
        nf: 32
  - model:
      name: SR_FastEDSR_Multi
      checkpoint_name: SR_FastEDSR_jpeg_4_64
      params:
        num_blocks: 4
        nf: 64
  - model:
      name: SR_FastEDSR_Multi
      checkpoint_name: SR_FastEDSR_jpeg_4_128
      params:
        num_blocks: 4
        nf: 128